### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by hiroshikado** [hiroshikado/chat-space3#10]
# IPアドレス
54.199.14.75

**Comment by miyu-yamamoto** [comment]
嘉戸さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**① サイドバーに表示されるグループ名と最新のメッセージが見切れている**
**② メッセージ送信フォームにカーソルを当てた際の、青枠の大きさが見本と相違
　かつ、ファイルを選択するアイコンの位置が上に寄っていてずれている**
**③ Sendボタンの色が見本と相違している**
<img width="1013" alt="スクリーンショット 2020-06-29 16 14 43" src="https://user-images.githubusercontent.com/59544869/85984509-40faf900-ba24-11ea-94c9-ea1a46c9c802.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by hiroshikado** [comment]
ご指摘頂いた３点、修正しました！
確認お願いしたします

**Comment by naru6117** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項はしっかり修正されていました！
ありがとうございます(^^)
新たに以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**・ピンクで囲った箇所に、カリキュラムで指定されている#eeeeeeの色をつけましょう**

### [修正箇所の現在の画像]
<img width="649" alt="スクリーンショット 2020-06-30 10 06 53" src="https://user-images.githubusercontent.com/49669977/86071244-bcf35080-bab9-11ea-87b8-d59e8cfa02ce.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by hiroshikado** [comment]
ご指摘の箇所(下線の追加)、修正しました！

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！
